apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscale-app
  labels:
    app: cloudscale-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudscale-app
  template:
    metadata:
      labels:
        app: cloudscale-app
    spec:
      containers:
        - name: cloudscale-app
          image: cloudscalesrracr2026.azurecr.io/cloudscale-app:v1.0.0
          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20